//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLangCV.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CV {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CV() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiLangCV.App_GlobalResources.CV", typeof(CV).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;http://www.pharmplanet.com.ua&quot; target=&quot;_blank&quot;&gt;Pharmplanet. Kyiv, Ukraine.&lt;/a&gt;.
        /// </summary>
        public static string mw_1_exp_company {
            get {
                return ResourceManager.GetString("mw_1_exp_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software support specialist.
        /// </summary>
        public static string mw_1_exp_pos {
            get {
                return ResourceManager.GetString("mw_1_exp_pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Responsibility:&lt;/p&gt;
        ///&lt;p&gt;- Bug fixing in stored procedures (Firebird).&lt;/p&gt;
        ///&lt;p&gt;- Creating and tuning reports.&lt;/p&gt;.
        /// </summary>
        public static string mw_1_exp_resp {
            get {
                return ResourceManager.GetString("mw_1_exp_resp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November 2011 - June 2012 (8 month’s).
        /// </summary>
        public static string mw_1_exp_time {
            get {
                return ResourceManager.GetString("mw_1_exp_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;http://fleettech.com.ua/&quot; target=&quot;_blank&quot;&gt;Fleettech. Kyiv, Ukraine.&lt;/a&gt;.
        /// </summary>
        public static string mw_2_exp_company {
            get {
                return ResourceManager.GetString("mw_2_exp_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backend developer.
        /// </summary>
        public static string mw_2_exp_pos {
            get {
                return ResourceManager.GetString("mw_2_exp_pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Responsibility:&lt;/p&gt;
        ///&lt;p&gt;- Analyzing user requirements&lt;/p&gt;
        ///&lt;p&gt;- Developing physical and logical data models and implements data architectures.&lt;/p&gt;
        ///&lt;p&gt;- Creating stored procedures, Triggers, Views, Functions.&lt;/p&gt;
        ///&lt;p&gt;- Development of analytical reports.&lt;/p&gt;
        ///&lt;p&gt;- Migrate data into new database from Firebird and  Excell.&lt;/p&gt;
        ///&lt;p&gt;- Business process automation using stored procedures and Jobs.&lt;/p&gt;
        ///&lt;p&gt;- Writing WebAPI controllers using Entity Framework.&lt;/p&gt;.
        /// </summary>
        public static string mw_2_exp_resp {
            get {
                return ResourceManager.GetString("mw_2_exp_resp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June 2012 - July 2017 (5 years).
        /// </summary>
        public static string mw_2_exp_time {
            get {
                return ResourceManager.GetString("mw_2_exp_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;https://www.luckylandgaming.com/&quot; target=&quot;_blank&quot;&gt;Lacky land gaming. Kyiv, Ukraine.&lt;/a&gt;.
        /// </summary>
        public static string mw_3_exp_company {
            get {
                return ResourceManager.GetString("mw_3_exp_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-SQL developer.
        /// </summary>
        public static string mw_3_exp_pos {
            get {
                return ResourceManager.GetString("mw_3_exp_pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Responsibility:&lt;/p&gt;
        ///&lt;p&gt;- Development of a new normalized table structure. Normalization of already existing tables.&lt;/p&gt;
        ///&lt;p&gt;- Creating stored procedures, Triggers, Views, Functions for new functionality.&lt;/p&gt;
        ///&lt;p&gt;- Creating and maintaining SQL Server Jobs&lt;/p&gt;
        ///&lt;p&gt;- Database tuning. Manage indexes and optimizing queries.&lt;/p&gt;
        ///&lt;p&gt;- Manage DDL triggers.&lt;/p&gt;
        ///&lt;p&gt;- Cross database data migration.&lt;/p&gt;.
        /// </summary>
        public static string mw_3_exp_resp {
            get {
                return ResourceManager.GetString("mw_3_exp_resp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July 2017 - present time.
        /// </summary>
        public static string mw_3_exp_time {
            get {
                return ResourceManager.GetString("mw_3_exp_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information.
        /// </summary>
        public static string mw_add {
            get {
                return ResourceManager.GetString("mw_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;As SQL Developer, I have a good practice of development database schema. I used memory-optimized  tables, worked with JSON and XML in SQL. I worked with new project where all business - logic was in SQL. Also I have experience with high-loaded databases (tables more than 10GB). Participated in the project as a software architect. Were developed by me stored procedures for complex mathematical calculations, search in all string values in DB, Database DDL logger.  &lt;/p&gt;
        ///&lt;p&gt;I have analytical skills, which I [rest of string was truncated]&quot;;.
        /// </summary>
        public static string mw_add_info {
            get {
                return ResourceManager.GetString("mw_add_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Aviation University.
        /// </summary>
        public static string mw_edu_1_name {
            get {
                return ResourceManager.GetString("mw_edu_1_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyiv, Ukraine.
        /// </summary>
        public static string mw_edu_1_place {
            get {
                return ResourceManager.GetString("mw_edu_1_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software  Engineering, Bachelor.
        /// </summary>
        public static string mw_edu_1_rank {
            get {
                return ResourceManager.GetString("mw_edu_1_rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish year 2016.
        /// </summary>
        public static string mw_edu_1_time {
            get {
                return ResourceManager.GetString("mw_edu_1_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olexandrian Polytechnic College.
        /// </summary>
        public static string mw_edu_2_name {
            get {
                return ResourceManager.GetString("mw_edu_2_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olexandria, Ukraine.
        /// </summary>
        public static string mw_edu_2_place {
            get {
                return ResourceManager.GetString("mw_edu_2_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software  Engineering, junior specialist.
        /// </summary>
        public static string mw_edu_2_rank {
            get {
                return ResourceManager.GetString("mw_edu_2_rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish year 2009.
        /// </summary>
        public static string mw_edu_2_time {
            get {
                return ResourceManager.GetString("mw_edu_2_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string mw_education {
            get {
                return ResourceManager.GetString("mw_education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiences.
        /// </summary>
        public static string mw_experiences {
            get {
                return ResourceManager.GetString("mw_experiences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language proficiency.
        /// </summary>
        public static string mw_laguages {
            get {
                return ResourceManager.GetString("mw_laguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;English&lt;/b&gt; - intermediate.
        /// </summary>
        public static string mw_lang_en {
            get {
                return ResourceManager.GetString("mw_lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Ukrainian&lt;/b&gt; - fluent.
        /// </summary>
        public static string mw_lang_ru {
            get {
                return ResourceManager.GetString("mw_lang_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Russian&lt;/b&gt; - fluent.
        /// </summary>
        public static string mw_lang_ua {
            get {
                return ResourceManager.GetString("mw_lang_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills &amp; Proficiency.
        /// </summary>
        public static string mw_skills_title {
            get {
                return ResourceManager.GetString("mw_skills_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string sb_contacts {
            get {
                return ResourceManager.GetString("sb_contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string sb_dob {
            get {
                return ResourceManager.GetString("sb_dob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sirotkin Dmytro.
        /// </summary>
        public static string sb_name {
            get {
                return ResourceManager.GetString("sb_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string sb_other {
            get {
                return ResourceManager.GetString("sb_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-SQL developer.
        /// </summary>
        public static string sb_position {
            get {
                return ResourceManager.GetString("sb_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string sb_region {
            get {
                return ResourceManager.GetString("sb_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyiv.
        /// </summary>
        public static string sb_region_name {
            get {
                return ResourceManager.GetString("sb_region_name", resourceCulture);
            }
        }
    }
}
